# .github/workflows/ci.yml
name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  type-check:
    runs-on: ubuntu-latest

    steps:
      # 使用自定义 GitHub Action 设置 Node.js 并安装依赖
      - name: Setup and Install Dependencies
        uses: ./common-steps.yml # 引用公共步骤

      # 执行 TypeScript 类型检查
      - name: Type-check with tsc
        run: npm run type-check # 运行类型检查命令

  test:
    runs-on: ubuntu-latest

    steps:
      # 使用自定义 GitHub Action 设置 Node.js 并安装依赖
      - name: Setup and Install Dependencies
        uses: ./common-steps.yml

      # 执行单元测试
      - name: Run unit tests
        run: npm run test # 运行单元测试
