name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      # 步骤 1: 检出代码
      - name: Checkout code
        uses: actions/checkout@v2

      # 步骤 2: 设置 Node.js 环境
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      # 步骤 3: 安装依赖
      - name: Install dependencies
        run: npm install

      # 步骤 4: 运行 ESLint 检查
      - name: Run ESLint
        run: npm run lint # 假设你的 `package.json` 中有配置 lint 命令

  type-check:
    runs-on: ubuntu-latest
    needs: eslint # 确保 type-check 依赖 eslint 作业

    steps:
      # 步骤 1: 检出代码
      - name: Checkout code
        uses: actions/checkout@v2

      # 步骤 2: 设置 Node.js 环境
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      # 步骤 3: 安装依赖
      - name: Install dependencies
        run: npm install

      # 步骤 4: 进行 TypeScript 类型检查
      - name: Type-check with tsc
        run: npm run type-check # 运行类型检查命令

  unit-test:
    runs-on: ubuntu-latest
    needs: eslint # 确保 test 依赖 eslint 作业

    steps:
      # 步骤 1: 检出代码
      - name: Checkout code
        uses: actions/checkout@v2

      # 步骤 2: 设置 Node.js 环境
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      # 步骤 3: 安装依赖
      - name: Install dependencies
        run: npm install

      # 步骤 4: 运行单元测试
      - name: Run unit tests
        run: npm run test # 运行单元测试命令
