name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  type-check:
    runs-on: ubuntu-latest

    steps:
      # 步骤 1: 检出代码
      - name: Checkout code
        uses: actions/checkout@v2

      # 步骤 2: 设置 Node.js 环境
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      # 步骤 3: 安装依赖
      - name: Install dependencies
        run: npm install

      # 步骤 4: 进行 TypeScript 类型检查
      - name: Type-check with tsc
        run: npm run type-check # 运行类型检查命令

  test:
    runs-on: ubuntu-latest
    needs: type-check # 这个作业依赖于 type-check 作业的成功

    steps:
      # 步骤 1: 检出代码
      - name: Checkout code
        uses: actions/checkout@v2

      # 步骤 2: 设置 Node.js 环境
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      # 步骤 3: 安装依赖
      - name: Install dependencies
        run: npm install

      # 步骤 4: 运行单元测试
      - name: Run unit tests
        run: npm run test # 运行单元测试命令
